package dev.cuprum.catalogtool;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Deterministically generates {@code CuprumCatalog.java} from the validated catalog.
 * The output depends only on the catalog contents (no timestamps, no environment).
 */
public final class CatalogCodegen {
    private CatalogCodegen() {
    }

    public static String generateSource(JsonObject catalog, String packageName) {
        List<String> ids = new ArrayList<>();
        for (JsonElement element : catalog.getAsJsonArray("entries")) {
            ids.add(element.getAsJsonObject().get("id").getAsString());
        }
        String sha256 = CanonicalJson.sha256(catalog);

        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Cuprum catalog codegen (generateCatalog task). DO NOT EDIT.\n");
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import java.util.List;\n\n");
        sb.append("/** Build-time snapshot of catalog/catalog.json. */\n");
        sb.append("public final class CuprumCatalog {\n");
        sb.append("    /** SHA-256 of the canonical (sorted-key, compact) JSON form of catalog/catalog.json. */\n");
        sb.append("    public static final String CATALOG_SHA256 = \"").append(sha256).append("\";\n\n");
        sb.append("    /** All catalog entry ids, in file (ascending) order. */\n");
        sb.append("    public static final List<String> IDS = List.of(\n");
        for (int i = 0; i < ids.size(); i++) {
            sb.append("            \"").append(ids.get(i)).append('"');
            sb.append(i < ids.size() - 1 ? ",\n" : "\n");
        }
        sb.append("    );\n\n");
        sb.append("    public static final int ENTRY_COUNT = ").append(ids.size()).append(";\n\n");
        sb.append("    private CuprumCatalog() {\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    public static Path writeSource(Path catalogFile, String packageName, Path outputRoot) throws IOException {
        JsonObject catalog = CatalogValidator.parseObject(catalogFile);
        String source = generateSource(catalog, packageName);
        Path target = outputRoot;
        for (String part : packageName.split("\\.")) {
            target = target.resolve(part);
        }
        Files.createDirectories(target);
        Path file = target.resolve("CuprumCatalog.java");
        // Only touch the file when contents change to keep incremental builds stable.
        if (!Files.exists(file) || !Files.readString(file, StandardCharsets.UTF_8).equals(source)) {
            Files.writeString(file, source, StandardCharsets.UTF_8);
        }
        return file;
    }
}
